---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.8-wheezy

inputs:
  - name: my-executable

run:
  path: bash
  args:
    - -c
    - |
      chmod +x my-executable/my-executable-*
      ./my-executable/my-executable-*
